### PR TITLE
base32 address support

### PR DESCRIPTION
**Pull request by afk11**
the bare bones encoding logic. needs follow up PR for more convenient functions, situated in blocktrail/bitcoinjs-lib (where we use this package)

### CODE REVIEW

**Comment by dabura667** [comment]
LGTM

**Comment by afk11** [comment]
@dabura667 Not sure where this belongs, I'd be tempted to separate it into a separate repo.. initially it seemed worth targeting this repo as we already have that es5 build included and used downstream (I was lazy that day), but since it's the operations need a bigint library, it makes a little less sense to target here. 

I'll see if bitcoinjs fancies a new repository, otherwise I'll probably create a separate repo here with just cash address support

**Comment by dabura667** [comment]
@afk11 dcousens mentioned forking it off....

Do you want to make a bitcoinjs-forks-lib and maintain it?

The problem is that none of us want to maintain it... lol.

and also if we make it an explicit fork about bitcoin forks,  we might end up having to maintain a bajillion forks and all their different replay protections........ though it could be a rule that SIGHASH_FORKID only or something...

either way, our exchange was wondering how we were going to handle the new address format for cash, so this helps a lot.

**Comment by dabura667** [comment]
maybe `forkidjs-lib`?

**Comment by dabura667** [comment]
looks like "for kids"... kek

**Comment by afk11** [comment]
Created github.com/btccom/cashaddress-js for it and published `cashaddress` on npm

**Pull request closed without merging**
